version: '3.9'
services:
  mysql1:
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      - "./initdb.d1:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
  mysql2:
    image: mysql:8
    ports:
      - "3307:3306"
    volumes:
      - "./initdb.d2:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
